name: GitHub Actions Workflow Linter

on:
  pull_request:

permissions:
  contents: read
  checks: write

concurrency:
  group: workflows-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflow-lint:
    name: Lint GitHub Workflows
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@PINNED_SHA
        with:
          persist-credentials: false

      - name: Check for .yml files
        shell: bash
        run: |
          echo "::group::Scan '.yml' in .github/workflows"
          set -eo pipefail
          mapfile -t ymls < <(find .github/workflows -type f -name "*.yml" | sort || true)
          if (( ${#ymls[@]} > 0 )); then
            for file in "${ymls[@]}"; do
              printf '::warning file=%s,title=Invalid Extension::The file "%s" should be renamed to ".yaml".\n' "$file" "$file"
            done
          else
            echo "All good: only .yaml files are present."
          fi
          echo "::endgroup::"

      - name: Install shellcheck
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -qq install shellcheck
      - name: Run actionlint
        uses: reviewdog/action-actionlint@PINNED_SHA
        env:
          SHELLCHECK_OPTS: -S error
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          tool_name: "actionlint"
          level: error
          filter_mode: nofilter
          fail_level: error
          actionlint_flags: ./.github/workflows

      - name: Run ghalint
        uses: koki-develop/github-actions-lint/ghalint@PINNED_SHA
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          tool_name: "ghalint"
          level: error

      - name: Run zizmor
        uses: koki-develop/github-actions-lint/zizmor@PINNED_SHA
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          tool_name: "zizmor"
          persona: auditor