name: Workflows quality gate

on:
  push:
    paths:
      - ".github/workflows/*"
  pull_request:
    paths:
      - ".github/workflows/*"
  workflow_dispatch:

concurrency:
  group: workflows-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-filenames:
    name: Enforce .yaml (no .yml allowed)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fail if any .yml files exist under .github/workflows
        shell: bash
        run: |
          set -eo pipefail
          mapfile -t ymls < <(find .github/workflows -type f -name "*.yml" | sort || true)
          
          if (( ${#ymls[@]} > 0 )); then
            echo "::group::Found .yml files that must be renamed to .yaml"
            
            for file in "${ymls[@]}"; do
              echo "::error file=${file},title=Invalid Extension::The file '${file}' must be renamed to '.yaml'."
            done
            
            echo "::endgroup::"
            exit 1
          fi
          
          echo "All good: only .yaml files are present."

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    needs: check-filenames
    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint via reviewdog
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          filter_mode: file

  yamllint:
    name: yamllint (workflows)
    runs-on: ubuntu-latest
    needs: check-filenames
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          strict: true
          file_or_dir: ".github/workflows"
