---
name: Workflows quality gate
run-name: Workflows quality gate

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - ".github/workflows/*"
      - "config/*.yml"
  pull_request:
    paths:
      - ".github/workflows/*"
      - "config/*.yml"
  workflow_dispatch:

concurrency:
  group: workflows-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # .yaml が混ざっていたら失敗（.yml に統一）
  check-filenames:
    name: Enforce .yml (no .yaml allowed)
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Fail if any .yaml files exist under .github/workflows
        shell: bash
        run: |
          set -eo pipefail
          mapfile -t yamls < <(find .github/workflows -type f -name "*.yaml" | sort || true)
          if (( ${#yamls[@]} > 0 )); then
            echo "::group::Found .yaml files that must be renamed to .yml"
            for file in "${yamls[@]}"; do
              echo "::error file=${file},title=Invalid Extension::The file '${file}' must be renamed to '.yml'."
            done
            echo "::endgroup::"
            echo "Example:"
            echo "  git mv .github/workflows/workflow.yaml .github/workflows/workflow.yml"
            exit 1
          fi
          echo "✅ All good: only .yml files are present."

  # GitHub Actions ワークフロー専用の静的解析
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    needs: check-filenames
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) latest /usr/local/bin

      - name: Running actionlint
        run: actionlint .github/workflows/*.yml

  # YAML 構文/スタイルのlint（設定ファイルも一緒にチェック）
  yamllint:
    name: yamllint (workflows & config)
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    needs: check-filenames
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ubuntu-24.04 には yamllint が入っています（なければ apt/pip で導入してください）
      - name: Running yamllint
        run: yamllint -c config/yamllint_config.yml .github/workflows/*.yml config/*.yml
